1807c_git/git_cs/urls.py
from django.urls import path, include
from django.views.generic.base import TemplateView
urlpatterns = [
    path('',TemplateView.as_view(template_name='index.html')),
    path('shijian/', include('shijian.urls')),
]

chenghao/urls.py
from django.urls import path
from  chenghao import views


app_name = 'chenghao'
urlpatterns = [
    path('chenghao/',views.ch,name ='chenghao')
]

dusen/urls.py
from django.urls import path, include
from . import views
app_name='dusen'

urlpatterns = [
    path('',views.index,name='index'),
    path('dusen/',views.dusen,name='dusen')
]

fxy/urls.py
from django.urls import path
from fxy import views

app_name = 'fxy'
urlpatterns = [
    path('fxy/',views.fxy,name='fxy')
]

git_cs/urls.py
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [

    path('lishan',include('lishan.urls')),
    path('',TemplateView.as_view(template_name='index.html')),


    path('huoyanan/',include('huoyanan.urls')),

    path('klq/',include('klq.urls')),
    path('hbj/',include('hbj.urls')),
    path('dusen/',include('dusen.urls')),
    path('zhanghao/',include('zhanghao.urls')),
    path('lilei/', include('lilei.urls')),


    # path('zhanghao/',include('zhanghao.urls')),

    #path('zhanghao/',include('zhanghao.urls')),



    # path('zhanghao/',include('zhanghao.urls')),




    path('fxy/',include('fxy.urls')),

    path('hxd/', include('houxiaodong.urls')),


    path('guanliang/', include('guanliang.urls')),






    # path('hxd/', include('houxiaodong.urls')),


    #path('hxd/', include('houxiaodong.urls')),


    path('wsw/',include('wsw.urls')),



    path('houjunjie/', include('houjunjie.urls')),


    path('wangmengli/', include('wangmwngli.urls')),
    path('gonghongyi/', include('guohongyi.urls')),



    path('slq/', include('slq.urls')),




    
    path('mazhen/',include('mazhen.urls')),
    path('liyichao',include('liyichao.urls')),
    path('shijian/',include('shijian1807.urls')),



    path('chenghao/',include('chenghao.urls')),



    # path('zhangruiqiang/',include('zhangruiqiang.urls'))

    # path('zhangruiqiang/',include('zhangruiqiang.urls')),





    path("sxh/",include("sxh.urls")),




    path('zhangruiqiang/',include('zhangruiqiang.urls')),




    # path('zhangruiqiang/',include('zhangruiqiang.urls')),




    path('wjj/',include('wangjunjie.urls')),

]

guanliang/urls.py
from django.urls import path
from guanliang import views

app_name = 'guanliangliang'
urlpatterns = [
    path('guanliang/', views.index, name='guan')
]

guohongyi/urls.py
from django.urls import path, include
from guohongyi import views
app_name='guohongyi'

urlpatterns = [

    path('guohongyi/',views.guohongyi,name='guohongyi')
]

hbj/urls.py
from django.urls import path
from hbj import views

app_name='hbj'
urlpatterns = [
    path('hbj/',views.hbj,name='hbj')
]

houjunjie/urls.py
from houjunjie import views
from django.urls import path
app_name = 'houjunjie'
urlpatterns = [
    path('', views.houjunjie, name='houjunjie')
]

houxiaodong/urls.py
from django.urls import path
from houxiaodong import views

app_name = 'hxd'
urlpatterns = [
    path('hxd/', views.hxd, name='hxd'),
]

huoyanan/urls.py
from django.urls import path
from huoyanan import views
app_name ='huoyanan'
urlpatterns=[
    path("huoyanan/",views.huoyanan,name="huoyanan"),

]

klq/urls.py
from klq import views
from django.urls import path, include

app_name = 'klq'

urlpatterns=[
    path('klq/',views.klq,name='klq'),
]

lilei/urls.py
from django.urls import path, include
from . import views
app_name='lilei'

urlpatterns = [
    path('',views.index,name='index'),
    path('lilei/',views.lilei,name='lilei')
]

lishan/urls.py
from django.urls import path, include
from . import views
app_name='lishan'

urlpatterns = [
    path('',views.index,name='index'),
    path('lishan/',views.lishan,name='lishan')
]

liyichao/urls.py
from django.urls import path, include
from django.views.generic.base import TemplateView
from . import views
app_name='liyichao'
urlpatterns = [
    path('',views.index,name='index'),
    path('liyichao/',views.liyichao,name='liyichao')
]

mazhen/urls.py
from django.urls import path, include
from . import views
app_name='mazhen'

urlpatterns = [
    path('',views.index,name='index'),
    path('mazhen/',views.mazhen,name='mazhen')
]

shijian1807/urls.py
from django.urls import path, include
from . import views
app_name='shijian'

urlpatterns = [
    path('',views.index,name='index'),
    path('shijian/',views.shijian,name='shijian')
]

slq/urls.py
from django.urls import path, include
from . import views
app_name='slq'

urlpatterns = [
    path('',views.slq,name='slq')
]

sxh/urls.py
from django.urls import path
from sxh import views
app_name = 'sxh'
urlpatterns = [
    path("sxh/",views.sxh,name = 'sxh')
]

wangjunjie/urls.py
from django.urls import path
from wangjunjie import views

app_name='wangjunjie'
urlpatterns = [
    path('wangjunjie/',views.wangjunjie,name='wangjunjie')
]

wangmwngli/urls.py
#__auter:王梦丽
from django.urls import path
from wangmwngli import views

app_name = 'wangmengli'
urlpatterns = [
    path('wangmengli/', views.index, name='wangmengli')
]

wsw/urls.py
from django.urls import path, include
from django.views.generic.base import TemplateView
from wsw import views

app_name = 'wsw'

urlpatterns = [
    path('',views.index,name='index'),
    path('wsw/',views.index2,name='wsw'),
]

zhanghao/urls.py
from django.urls import path
#rom guanliangliang import views
from zhanghao import views
app_name = 'zhanghao'

urlpatterns = [
    path('zhanghao/', views.zhanghao, name='zhanghao')
]

zhangruiqiang/urls.py
from django.urls import path

from zhangruiqiang import views

app_name='zhangruiqiang'



urlpatterns = [

    path('zhangruiqiang/',views.index,name='zhangruiqiang')
]

1807c_git/shijian/models.py
from django.db import models

# Create your models here.

dusen/models.py
from django.db import models

# Create your models here.

fxy/models.py
from django.db import models

# Create your models here.

guanliang/models.py
from django.db import models

# Create your models here.

hbj/models.py
from django.db import models

# Create your models here.

houjunjie/models.py
from django.db import models

# Create your models here.

houxiaodong/models.py
from django.db import models

# Create your models here.

huoyanan/models.py
from django.db import models

# Create your models here.

klq/models.py
from django.db import models

# Create your models here.

lilei/models.py
from django.db import models

# Create your models here.

lishan/models.py
from django.db import models

# Create your models here.

liyichao/models.py
from django.db import models

# Create your models here.

mazhen/models.py
from django.db import models

# Create your models here.

slq/models.py
from django.db import models

# Create your models here.

sxh/models.py
from django.db import models

# Create your models here.

wangjunjie/models.py
from django.db import models

# Create your models here.

wsw/models.py
from django.db import models

# Create your models here.

zhanghao/models.py
from django.db import models

# Create your models here.

1807c_git/shijian/views.py
from django.shortcuts import render

# Create your views here.
def index(request):

    return render(request, 'shijian.html')

dusen/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'index.html')

def dusen(request):
    return render(request,'dusen.html')

templates/ch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    程皓
</body>
</html>

templates/dusen.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>dusen</title>
</head>
<body>
<h1>杜森</h1>
</body>
</html>

templates/fxy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    范向阳
</body>
</html>

templates/houjunjie.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>侯俊杰</title>
</head>
<body>
<h1>侯俊杰</h1>
</body>
</html>

templates/houxiaodong.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>侯晓栋</h1>
</body>
</html>

templates/huoyanan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>霍</title>
</head>
<body>
<h1>霍亚楠</h1>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>1807C    Git     测试项目</h1>
<ul>
    <li><a href="{% url 'huoyanan:huoyanan' %}">霍亚楠</a></li>
    <li><a href="{% url 'huoyanan:huoyanan' %}">霍亚楠</a></li>
    <li><a href="{% url 'klq:klq' %}">孔令琪</a></li>
    <li></li>
    <li><a href="{% url 'hbj:hbj' %}">韩宾杰</a></li>
    <li><a href="{% url 'chenghao:chenghao' %}">程皓</a></li>
    <li><a href="{% url 'wangjunjie:wangjunjie' %}">王俊杰</a></li>
    <li></li>
    <li><a href="{% url 'liyichao:liyichao' %}">李艺超</a></li>
    <li><a href="{% url 'fxy:fxy' %}">范向阳</a></li>
    <li><a href="{% url 'guanliangliang:guan' %}">关亮</a></li>
    <li><a href="{% url 'lilei:lilei' %}">李磊</a></li>
    <li><a href="{% url 'lishan:lishan' %}">李姗</a></li>
    <li><a href="{% url 'sxh:sxh' %}">sxh</a></li>
    <li></li>
    <li><a href="{%url 'zhanghao:zhanghao'%}">张浩</a></li>
    <li><a href="{% url 'wsw:wsw' %}">吴双伟</a></li>
    <li><a href="{% url 'hxd:hxd' %}">侯晓栋</a></li>
    <li><a href="{% url 'houjunjie:houjunjie' %}">侯俊杰</a></li>
    <li><a href="{% url 'wangmengli:wangmengli' %}">王梦丽</a></li>
    <li><a href="{% url 'houjunjie:houjunjie' %}">侯俊杰</a></li>
    <li><a href="{% url 'wangmengli:wangmengli' %}">王梦丽</a></li>
    <li><a href="{% url 'guohongyi:guohongyi' %}">guohongyi</a></li>
    <li><a href="{% url 'shijian:shijian' %}">石坚</a></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
	 <li><a href="{% url 'mazhen:mazhen' %}">马真</a></li>
    <li></li>
    <li></li>
    <li><a href="{% url 'zhangruiqiang:zhangruiqiang' %}">张瑞强</a> </li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li><a href="{%url 'dusen:dusen'%}">杜森</a></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
</ul>

</body>
</html>

templates/klq.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>孔令琪</h1>
</body>
</html>

templates/lishan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>李姗</h1>
</body>
</html>

templates/slq.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>cao nizui</h1>
</body>
</html>

templates/wangmengli.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>王梦丽</h1>
</body>
</html>

templates/wsw.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>吴双伟</h1>
</body>
</html>

templates/zhanghao.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>zhanghao</title>
</head>
<body>
<h1>张浩</h1>
</body>
</html>

templates/zrq.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>张瑞强</h1>
</body>
</html>